# Generated by Django 4.2.6 on 2023-11-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_alter_carowner_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ManyToManyField(through='project_first_app.Possesion', to='project_first_app.carowner'),
        ),
    ]
