# Generated by Django 4.2.6 on 2023-11-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0004_alter_carowner_options_alter_carowner_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
