# Generated by Django 4.2.6 on 2023-11-02 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_firts_app', '0004_alter_carowner_options_alter_carowner_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carowner',
            name='cars',
        ),
        migrations.RemoveField(
            model_name='carowner',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='carowner',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='car',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='car_owner',
        ),
        migrations.RemoveField(
            model_name='sertificate',
            name='id_owner',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='CarOwner',
        ),
        migrations.DeleteModel(
            name='Ownership',
        ),
        migrations.DeleteModel(
            name='Sertificate',
        ),
    ]
