site_name: "Лабораторные работы"

theme:
  name: material

nav:
  - "№1: Сокеты":
      - lw1/index.md
      - lw1/task_1.md
      - lw1/task_2.md
      - lw1/task_3.md
      - lw1/task_4.md
      - lw1/task_5.md
  - "№2: Django":
      - lw2/index.md
      - lw2/task.md
  - "№3: Django rest":
      - pr3/practical_work.md
