site_name: "Лабораторные работы Макуниной Арины"

theme:
  name: material

repo_url: https://github.com/arnmacing/ITMO_ICT_WebDevelopment_2023-2024

nav:
  - "№1: Сокеты":
      - lw1/index.md
      - lw1/task_1.md
      - lw1/task_2.md
      - lw1/task_3.md
      - lw1/task_4.md
      - lw1/task_5.md
  - "№2: Django":
      - lw2/index.md
      - lw2/task.md
