# Generated by Django 4.2.5 on 2023-10-01 08:40

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hotelapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date_until",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="guest",
            name="country",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="guest",
            name="photo",
            field=models.ImageField(
                blank=True, default="/static/img/user.svg", upload_to="media/"
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="thumbnail",
            field=models.ImageField(upload_to="media/"),
        ),
        migrations.AlterField(
            model_name="room",
            name="commodities",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Bathroom", "Bathroom"),
                    ("Swimming pool", "Swimming pool"),
                    ("Parking", "Parking"),
                    ("Wi-Fi", "Wi-Fi"),
                    ("Air conditioner", "Air conditioner"),
                    ("Room service", "Room service"),
                    ("Breakfast", "Breakfast"),
                    ("Balcony", "Balcony"),
                    ("Refrigerator", "Refrigerator"),
                ],
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="thumbnail",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
