# Generated by Django 4.2.5 on 2023-10-31 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project_first_app", "0002_alter_driver_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownership",
            name="car",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="project_first_app.car",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ownership",
            name="driver",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
