# Generated by Django 4.2.5 on 2023-10-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_first_app", "0004_alter_car_drivers_alter_driver_cars_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="driverlicence",
            name="date_of_release",
            field=models.DateField(),
        ),
    ]
