# Generated by Django 4.2.6 on 2023-10-29 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0006_alter_carowner_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carowner',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterUniqueTogether(
            name='carowner',
            unique_together=set(),
        ),
    ]
