# Generated by Django 4.2.6 on 2023-11-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0008_alter_carowner_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverslicense',
            name='IssueDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='BeginDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='EndDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
