# Generated by Django 3.2.22 on 2023-10-15 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField()),
                ('date_deadline', models.DateField()),
                ('task', models.CharField(max_length=200)),
                ('penalty', models.CharField(max_length=200)),
                ('discipline_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intestines.discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=1)),
                ('homework_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intestines.homework')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars', models.ManyToManyField(to='intestines.StudentGrade')),
                ('discipline_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intestines.discipline')),
                ('student_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intestines.student')),
            ],
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intestines.teacher'),
        ),
        migrations.CreateModel(
            name='AssignedHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('student_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intestines.student')),
                ('work_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intestines.homework')),
            ],
        ),
    ]
