# Generated by Django 3.2.22 on 2023-10-15 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intestines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='homework_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intestines.assignedhomework'),
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='intestines.schoolgroup'),
        ),
    ]
