# Generated by Django 3.2.22 on 2023-10-15 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intestines', '0002_auto_20231016_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='schoolgroup_object',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='intestines.schoolgroup'),
        ),
    ]
