# Generated by Django 3.2.22 on 2023-10-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intestines', '0003_homework_schoolgroup_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolgroup',
            name='grade',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='schoolgroup',
            name='letter_id',
            field=models.CharField(default='Ъ', max_length=1),
        ),
    ]
