# Generated by Django 3.2.22 on 2023-10-15 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intestines', '0004_auto_20231016_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedhomework',
            name='student_object',
        ),
        migrations.AddField(
            model_name='assignedhomework',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
