# Generated by Django 3.2.18 on 2023-10-16 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intestines', '0006_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentperformance',
            old_name='cars',
            new_name='grades',
        ),
    ]
