# Generated by Django 4.2.6 on 2023-10-21 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project_first_app", "0002_owner_owned_cars_alter_ownership_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_license",
                to="project_first_app.owner",
            ),
        ),
    ]
