site_name: Web-программирование
site_description: Лабораторная работа №3 по предмету Web-программирование
site_author: Бускина Алия

nav:
  - 'Главная страница': 'index.md'
  - 'Лабораторная работа': 'labwork.md'
  - 'Представления': 'views.md'
  - 'Сериализаторы': 'serializers.md'