# Generated by Django 4.2.7 on 2023-11-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ak_pr1_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='owners',
            field=models.ManyToManyField(through='ak_pr1_app.Ownership', to='ak_pr1_app.carowner'),
        ),
        migrations.AddField(
            model_name='carowner',
            name='cars',
            field=models.ManyToManyField(through='ak_pr1_app.Ownership', to='ak_pr1_app.car'),
        ),
    ]
