site_name: "Тарабанов Алексей K33402"
nav:
  - "Лабораторная": index.md
  - "Задание 1": task1.md
  - "Задание 2": task2.md
  - "Задание 3": task3.md
  - "Задание 4": task4.md
  - "Задание 5": task5.md

