site_name: Lb2, Pavlishina Irina, K33391
nav:
  - Home: index.md
  - Настройки сервера: first.md
  - Модели: second.md
  - Формы: third.md
  - Представления: fourth.md
  - Темплэйты: fith.md
  - Ссылки: sixth.md
  - Джанго-Админ: seventh.md

theme:
  name: mkdocs
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: ru