# Generated by Django 4.2.6 on 2023-10-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_travel_app', '0002_alter_flight_arrival_alter_flight_departure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='arrival_city',
            field=models.CharField(default='SPB', max_length=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_city',
            field=models.CharField(default='MSK', max_length=100),
        ),
    ]
