# Generated by Django 4.2.6 on 2023-10-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_alter_car_colour_alter_carowner_dateofbirth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='DateOfBirth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverslicense',
            name='IssueDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='BeginDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='EndDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
