# Generated by Django 4.2.6 on 2023-10-29 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0004_alter_carowner_options_alter_carowner_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carowner',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='carowner',
            unique_together={('username',)},
        ),
    ]
