# Generated by Django 4.2.6 on 2023-11-29 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0009_alter_driverslicense_issuedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverslicense',
            name='carowner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onwerships', to='project_first_app.car'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='carowner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onwerships', to=settings.AUTH_USER_MODEL),
        ),
    ]
