# Generated by Django 4.2.6 on 2023-10-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0005_alter_carowner_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carowner',
            unique_together={('username', 'LastName', 'FirstName')},
        ),
    ]
