site_name: Web Programming Documentation
theme: readthedocs 

nav: 
- Home: index.md
- ЛР1: 
  - Задание: lab1/task.md
  - Задание 1: lab1/task1.md 
  - Задание 2: lab1/task2.md 
  - Задание 3: lab1/task3.md
  - Задание 4: lab1/task4.md 
  - Задание 5: lab1/task5.md 

- ЛР2: 
  - Задание: lab2/task.md
  - Практическая работа: lab2/practice.md 
  - Главная страница: lab2/main_page_login.md
  - Отели: lab2/hotels.md
  - Бронирование: lab2/reservations.md 

- ЛР3: 
  - Задание: lab3/task.md
  - Практическая работа: lab3/practice.md
  - Модели: lab3/models.md
  - Serializers: lab3/serializers.md
  - Views: lab3/views.md
  - Swagger: lab3/swagger.md

- ЛР4: 
  - Задание: lab4/task.md
  - Регистрация: lab4/registration.md
  - Вход: lab4/login.md
  - Профиль: lab4/profile.md
  - Homepage: lab4/homepage.md
  - Animals: lab4/animals.md
  - Locations: lab4/locations.md
  - Shop: lab4/shop.md
  - Other zoos: lab4/other_zoos.md


