# Generated by Django 4.2.6 on 2023-10-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='driverlicence',
            name='date_of_issue',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='possesion',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='possesion',
            name='start_date',
            field=models.DateField(),
        ),
    ]
