# Generated by Django 4.2.6 on 2023-11-08 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races_table', '0002_user_has_racer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='raceconnection',
            unique_together={('racer', 'race')},
        ),
    ]
