# Generated by Django 4.2.7 on 2024-01-16 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='animals',
        ),
        migrations.AddField(
            model_name='animal',
            name='cleaner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cleaned_animals', to='system.worker'),
        ),
        migrations.AddField(
            model_name='animal',
            name='vet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vet_animals', to='system.worker'),
        ),
    ]
