# Generated by Django 4.2.6 on 2023-12-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_api', '0002_employeefloor_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('occupied', 'Occupied')], max_length=100),
        ),
    ]
