# Generated by Django 4.2.6 on 2023-12-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_api', '0002_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('cleaning', 'Cleaning')], max_length=100),
        ),
    ]
