# Generated by Django 4.2.6 on 2023-12-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_api', '0003_alter_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('occupied', 'Occupied'), ('cleaning', 'Cleaning')], max_length=100),
        ),
    ]
