# Generated by Django 4.2.6 on 2023-12-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_api', '0005_room_booked_by_room_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
        migrations.AddField(
            model_name='room',
            name='booking_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
