# Generated by Django 4.2.6 on 2024-01-04 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_api', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_occupant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupied_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
