# Generated by Django 4.2.6 on 2024-01-04 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_api', '0009_room_current_occupant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='room',
        ),
    ]
