# Generated by Django 4.2.7 on 2023-11-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdeeapp', '0010_customtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomToken',
        ),
    ]
