# Generated by Django 4.2.7 on 2023-11-25 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdeeapp', '0011_delete_customtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailydata',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='dailydata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userfood',
            name='food',
        ),
        migrations.RemoveField(
            model_name='userfood',
            name='user',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='DailyData',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='UserFood',
        ),
    ]
