# Generated by Django 4.2.7 on 2023-11-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdeeapp', '0014_tokenproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenProxy',
        ),
    ]
