# Generated by Django 4.2.7 on 2023-11-25 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tdeeapp', '0015_delete_tokenproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tdeeapp.profile'),
            preserve_default=False,
        ),
    ]
