# Generated by Django 4.2.7 on 2023-11-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdeeapp', '0018_alter_dailydata_user_alter_userfood_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailydata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userfood',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
