site_name: Lb3, Pavlishina Irina, K33391
nav:
  - Home: index.md
  - Настройки: first.md
  - Модели: second.md
  - Сериалайзеры: third.md
  - Представления: forth.md
  - Ссылки: fith.md

theme:
  name: mkdocs
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: ru