site_name: My Docs

theme:
  name: material

nav:
  - "Лабораторная работа 1":
      - lab1/ex1.md
      - lab1/ex2.md
      - lab1/ex3.md
      - lab1/ex4.md
      - lab1/ex5.md
  - "Лабораторная работа 2":
      - lab2/models.md
      - lab2/views.md
      - lab2/forms.md
      - lab2/urls.md
  - "Лабораторная работа 3":
      - lab3/practice3_1.md
      - lab3/views.md
      - lab3/filters.md
      - lab3/models.md
      - lab3/serializers.md
      - lab3/error.md