site_name: My Docs
site_url: https://example.com/
nav:
  - Home: index.md
  - Tasks:
    - 'Task 1': 'task1.md'
    - 'Task 2': 'task2.md'
    - 'Task 3': 'task3.md'
    - 'Task 4': 'task4.md'
    - 'Task 5': 'task5.md'
