# Generated by Django 4.2.7 on 2024-01-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='attending',
            field=models.ManyToManyField(null=True, related_name='students', to='lms_app.course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='teaching',
            field=models.ManyToManyField(null=True, related_name='teachers', to='lms_app.course'),
        ),
    ]
