# Generated by Django 4.2.7 on 2024-01-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_alter_user_attending_alter_user_teaching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='apply_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='reply_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='lesson_photos'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='subject_photos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='about_info',
            field=models.TextField(blank=True, default='A very interesting person', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='attending',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='lms_app.course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default='Moscow', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='Russia', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_media_link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='teaching',
            field=models.ManyToManyField(blank=True, null=True, related_name='teachers', to='lms_app.course'),
        ),
    ]
