# Generated by Django 4.2.7 on 2024-01-07 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_alter_application_apply_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['id']},
        ),
    ]
