# Generated by Django 4.2.7 on 2024-01-07 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_alter_course_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='Subject',
            new_name='subject',
        ),
    ]
