# Generated by Django 4.2.7 on 2023-11-02 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='owner',
        ),
    ]
