# Generated by Django 4.2.7 on 2023-11-02 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_remove_car_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ManyToManyField(through='project_first_app.Ownership', to=settings.AUTH_USER_MODEL),
        ),
    ]
