# Generated by Django 4.2.7 on 2023-11-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0003_car_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='carowner',
            name='home_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carowner',
            name='nationality',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='carowner',
            name='passport',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
