# Generated by Django 4.2.7 on 2023-12-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountaineering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='member_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
