# Generated by Django 4.2.7 on 2023-12-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountaineering', '0002_alter_group_member_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='outcome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
