site_name: Документация. Байков Иван. K33392
nav:
  - Лабораторная работа 1: lab1/lab_1.md
  - Лабораторная работа 2: lab2/lab_2.md
  - Лабораторная работа 3: lab3/lab_3.md
  - Лабораторная работа 4: lab4/lab_4.md
  - Практическая работа 3.1: practical/pw-3.1.md
