# Generated by Django 4.2.6 on 2023-10-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first_app', '0002_alter_car_state_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='owners',
            field=models.ManyToManyField(through='django_first_app.Own', to='django_first_app.owner'),
        ),
        migrations.AlterField(
            model_name='car',
            name='id_car',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='driver_license',
            name='date_issued',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='driver_license',
            name='id_license',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='owner',
            name='id_owner',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
