site_name: 'Отчет по первой лабораторной'

theme:
  name: material

nav:
  - 'Home': 'index.md'
  - 'Task_1': 'task_1.md'
  - 'Task_2': 'task_2.md'
  - 'Task_3': 'task_3.md'
  - 'Task_4': 'task_4.md'
  - 'Task_5': 'task_5.md'
