# Generated by Django 4.2.7 on 2023-11-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0022_remove_review_booking_review_bookingid_review_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='bookingid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
