# Generated by Django 4.2.7 on 2023-11-06 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0023_alter_review_bookingid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
    ]
