# Generated by Django 4.2.7 on 2023-11-06 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0024_remove_booking_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='bookingid',
        ),
        migrations.RemoveField(
            model_name='review',
            name='room',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.booking'),
        ),
    ]
