# Generated by Django 5.0.3 on 2024-03-13 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='climber',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alpinist_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='climber',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alpinists', to='club.club'),
        ),
        migrations.AddField(
            model_name='group',
            name='climb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='club.climb'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='alpinist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.climber'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='club.group'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guide_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='climb',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climbs', to='club.mentor'),
        ),
        migrations.AddField(
            model_name='route',
            name='mountain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='club.mountain'),
        ),
        migrations.AddField(
            model_name='climb',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climbs', to='club.route'),
        ),
    ]
