site_name: Митурский Богдан K33392
theme:
  name: material
  features:
    - navigation.indexes
  palette:
    scheme: slate
    primary: black
    accent: indigo
nav:
  - Лабораторная работа №3:
      - Оглавление: lab3/index.md
      - Задание №1: lab3/task1.md
      - Задание №2: lab3/task2.md
      - Задание №3: lab3/task3.md
      - Задание №4: lab3/task4.md
      - Результат: lab3/result/index.md
      - Вывод: lab3/conclusion.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html
plugins:
  - glightbox
