version: "3.4"

services:
  db:
    image: postgres:14.1
    container_name: postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - "5433:5432"

  be:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: be
    restart: always
    volumes:
      - ./src/:/src
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
