# Generated by Django 4.2.6 on 2023-11-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_soldtour_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
