# Generated by Django 4.2.7 on 2023-11-03 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_number', models.IntegerField()),
                ('cer_brand', models.CharField(max_length=20)),
                ('car_model', models.CharField(max_length=20)),
                ('car_color', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('car_owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('birthday', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.IntegerField()),
                ('license_type', models.CharField(max_length=10)),
                ('issue_date', models.DateField()),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Levashova_app.carowner')),
            ],
        ),
        migrations.CreateModel(
            name='CarOwn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('Car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Levashova_app.car')),
                ('CarOwner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Levashova_app.carowner')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='cars',
            field=models.ManyToManyField(through='Levashova_app.CarOwn', to='Levashova_app.carowner'),
        ),
    ]
