# Generated by Django 4.2.7 on 2023-11-04 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Levashova_app', '0002_rename_car_owner_id_carowner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='cer_brand',
            new_name='car_brand',
        ),
    ]
