# Generated by Django 4.2.7 on 2023-11-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Levashova_app', '0004_alter_car_state_number_alter_carowner_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_model',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='carown',
            old_name='Car',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='carown',
            old_name='CarOwner',
            new_name='car_owner',
        ),
    ]
