# Generated by Django 4.2.7 on 2023-11-04 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="tour_date",
        ),
        migrations.AddField(
            model_name="review",
            name="tour",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="tours_app.tour",
            ),
            preserve_default=False,
        ),
    ]
