# Generated by Django 4.2.7 on 2023-11-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traveler",
            name="tours",
            field=models.ManyToManyField(blank=True, related_name="Reservation", to="tours_app.tour"),
        ),
    ]
