# Generated by Django 4.2.7 on 2023-11-04 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours_app", "0002_remove_review_tour_date_review_tour"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="tour",
        ),
        migrations.AddField(
            model_name="review",
            name="tour_date",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="tours_app.tourdate",
            ),
            preserve_default=False,
        ),
    ]
