# Generated by Django 4.2.7 on 2023-11-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alpinism_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alpinist",
            name="birth_date",
            field=models.DateField(null=True),
        ),
    ]
