# Generated by Django 4.2.7 on 2023-11-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alpinism_app", "0002_alter_alpinist_birth_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alpinist",
            name="name",
        ),
        migrations.RemoveField(
            model_name="alpinist",
            name="surname",
        ),
        migrations.AlterField(
            model_name="alpinist",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="alpinist",
            name="last_name",
            field=models.CharField(max_length=50),
        ),
    ]
