# Generated by Django 4.2.7 on 2023-11-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alpinism_app", "0004_clubmembership_admin_confirmation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubmembership",
            name="date_from",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="clubmembership",
            name="date_to",
            field=models.DateField(null=True),
        ),
    ]
