# Generated by Django 4.2.7 on 2023-11-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alpinism_app", "0006_alter_clubmembership_date_to_alter_mountain_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="climbing",
            name="finish_date_fact",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="climbing",
            name="start_date_fact",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
