# Generated by Django 4.2.7 on 2023-11-21 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alpinism_app", "0007_alter_climbing_finish_date_fact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="climbing",
            name="max_participants",
            field=models.IntegerField(
                default=10, validators=[django.core.validators.MinValueValidator(2)]
            ),
        ),
    ]
