# Generated by Django 4.2.7 on 2023-11-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alpinism_app", "0008_climbing_max_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="climbing",
            name="cost",
            field=models.IntegerField(default=10000),
        ),
    ]
