# Generated by Django 4.2.7 on 2023-11-14 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('education', models.CharField(max_length=255, verbose_name='Образование')),
                ('work_experience', models.IntegerField(verbose_name='Стаж работы')),
                ('passport_info', models.CharField(max_length=255, verbose_name='Паспортные данные')),
                ('flight_authorization', models.BooleanField(default=False, verbose_name='Допуск к рейсу')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20, verbose_name='Номер рейса')),
                ('distance', models.IntegerField(verbose_name='Расстояние до пункта назначения')),
                ('departure_point', models.CharField(max_length=255, verbose_name='Пункт вылета')),
                ('destination_point', models.CharField(max_length=255, verbose_name='Пункт назначения')),
                ('departure_datetime', models.DateTimeField(verbose_name='Дата и время вылета')),
                ('arrival_datetime', models.DateTimeField(verbose_name='Дата и время прилета')),
                ('transit_landings', models.CharField(max_length=255, verbose_name='Транзитные посадки')),
                ('landing_points', models.CharField(max_length=255, verbose_name='Пункты посадки')),
                ('transit_landing_datetime', models.DateTimeField(verbose_name='Дата и время транзитных посадок')),
                ('sold_tickets', models.IntegerField(verbose_name='Количество проданных билетов')),
                ('airplanes', models.ManyToManyField(to='main.crew', verbose_name='Экипаж, обслуживающий рейс')),
            ],
        ),
        migrations.AddField(
            model_name='crew',
            name='members',
            field=models.ManyToManyField(to='main.crewmember', verbose_name='Члены экипажа'),
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер самолета')),
                ('plane_type', models.CharField(max_length=50, verbose_name='Тип самолета')),
                ('seats_capacity', models.IntegerField(verbose_name='Число мест')),
                ('flight_speed', models.IntegerField(verbose_name='Скорость полета')),
                ('airline_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company', verbose_name='Компания-авиаперевозчик')),
            ],
        ),
    ]
