# Generated by Django 4.2.6 on 2023-11-30 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_company_airlinecompany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='airplanes',
        ),
        migrations.RemoveField(
            model_name='route',
            name='arrival_datetime',
        ),
        migrations.RemoveField(
            model_name='route',
            name='departure_datetime',
        ),
        migrations.RemoveField(
            model_name='route',
            name='sold_tickets',
        ),
        migrations.RemoveField(
            model_name='route',
            name='transit_landing_datetime',
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_datetime', models.DateTimeField(verbose_name='Дата и время вылета')),
                ('arrival_datetime', models.DateTimeField(verbose_name='Дата и время прилета')),
                ('transit_landing_datetime', models.DateTimeField(verbose_name='Дата и время транзитных посадок')),
                ('sold_tickets', models.IntegerField(verbose_name='Количество проданных билетов')),
                ('airplanes', models.ManyToManyField(to='main.airplane', verbose_name='Самолеты, обслуживающие рейс')),
                ('crew', models.ManyToManyField(to='main.crew', verbose_name='Экипаж, обслуживающий рейс')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='main.route', verbose_name='Маршрут')),
            ],
        ),
    ]
