# Generated by Django 4.2.6 on 2023-12-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_route_airplanes_remove_route_arrival_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='transit_landing_datetime',
            field=models.DateTimeField(blank=True, verbose_name='Дата и время транзитных посадок'),
        ),
        migrations.AlterField(
            model_name='route',
            name='landing_points',
            field=models.CharField(blank=True, max_length=255, verbose_name='Пункты посадки'),
        ),
        migrations.AlterField(
            model_name='route',
            name='transit_landings',
            field=models.CharField(blank=True, max_length=255, verbose_name='Транзитные посадки'),
        ),
    ]
