# Generated by Django 4.2.6 on 2023-12-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_flight_transit_landing_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewmember',
            name='company',
            field=models.ManyToManyField(to='main.airlinecompany', verbose_name='Компания, в которой работает'),
        ),
    ]
