# Generated by Django 4.2.7 on 2023-11-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFirst_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='fullName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='pNumber',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='person',
            name='pSeries',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='tour',
            name='target',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tour',
            name='type',
            field=models.CharField(choices=[('AllIn', 'All inclusive'), ('T&A', 'Travel and accommodation')], max_length=30),
        ),
        migrations.AlterField(
            model_name='treaty',
            name='status',
            field=models.CharField(choices=[('w', 'awaiting confirmation'), ('a', 'approved'), ('r', 'rejected')], max_length=50),
        ),
    ]
