# Generated by Django 4.2.7 on 2023-11-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFirst_app', '0002_alter_person_fullname_alter_person_pnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='name',
            field=models.TextField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
