# Generated by Django 4.2.7 on 2023-11-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFirst_app', '0003_tour_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tour',
            name='target',
            field=models.CharField(max_length=40),
        ),
    ]
