# Generated by Django 4.2.7 on 2023-11-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFirst_app', '0004_alter_tour_name_alter_tour_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.TextField(default=12, max_length=1000),
            preserve_default=False,
        ),
    ]
