# Generated by Django 4.2.7 on 2023-11-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFirst_app', '0005_tour_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treaty',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='treaty',
            name='startDate',
            field=models.DateField(),
        ),
    ]
