# Generated by Django 4.2.7 on 2023-11-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFirst_app', '0006_alter_treaty_enddate_alter_treaty_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='treaty',
            name='cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treaty',
            name='pNum',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
