# Generated by Django 4.2.7 on 2023-11-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFirst_app', '0007_treaty_cost_treaty_pnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='tEndDate',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='tStartDate',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
