site_name: Lab №3 Злотникова Карина K33392
nav:
  - Home: index.md
  - Лпбораторная работа 1: lab1.md
  - Лпбораторная работа 2: lab2.md
  - Лпбораторная работа 3: lab3.md

theme:
  name: mkdocs
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: ru
