# Generated by Django 4.2.6 on 2023-10-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_first_app", "0002_alter_ownership_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="driverlicense",
            name="creation_date",
            field=models.DateField(),
        ),
    ]
