# Generated by Django 4.2.6 on 2023-10-31 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('class_dog', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ex', models.CharField(max_length=100)),
                ('date_b', models.DateField()),
                ('date_c', models.DateField()),
                ('type', models.CharField(choices=[('C1', 'CACIB'), ('C2', 'CAC'), ('M', 'MONO')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reg', models.DateField()),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.dog')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.exhibition')),
            ],
        ),
        migrations.AddField(
            model_name='exhibition',
            name='member',
            field=models.ManyToManyField(through='project_first_app.Participate', to='project_first_app.dog'),
        ),
        migrations.AddField(
            model_name='dog',
            name='owner_dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.owner'),
        ),
    ]
