# Generated by Django 4.2.7 on 2024-01-07 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_userprofile_favorite_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
    ]
