# Generated by Django 3.2 on 2023-12-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_cleaning_date_clean'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='staying_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
