# Generated by Django 4.2.5 on 2023-10-01 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("homework_board_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="fio",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="homework_board_app.group",
            ),
        ),
    ]
