# Generated by Django 4.2.5 on 2023-10-01 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("homework_board_app", "0004_user_delete_student"),
    ]

    operations = [
        migrations.RenameModel(old_name="User", new_name="Student",),
    ]
