# Generated by Django 4.2.5 on 2023-10-01 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homework_board_app", "0005_rename_user_student"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="teacher",),
    ]
