# Generated by Django 4.2.5 on 2023-10-01 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("homework_board_app", "0006_remove_student_teacher"),
    ]

    operations = [
        migrations.RemoveField(model_name="homework", name="assignment_text",),
        migrations.RemoveField(model_name="homework", name="date_of_issue",),
        migrations.RemoveField(model_name="homework", name="deadline_date",),
        migrations.RemoveField(model_name="homework", name="fines_information",),
        migrations.RemoveField(model_name="homework", name="students_who_completed",),
        migrations.RemoveField(model_name="homework", name="subject",),
        migrations.RemoveField(model_name="homeworksubmission", name="student",),
        migrations.RemoveField(model_name="student", name="homeworks_completed",),
        migrations.AddField(
            model_name="homework",
            name="student",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="HomeworkDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_issue", models.DateField()),
                ("deadline_date", models.DateField()),
                ("assignment_text", models.TextField()),
                ("fines_information", models.TextField(blank=True, null=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homework_board_app.subject",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="homework",
            name="homework_description",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="homework_board_app.homeworkdescription",
            ),
            preserve_default=False,
        ),
    ]
