# Generated by Django 4.2.5 on 2023-10-01 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homework_board_app", "0007_remove_homework_assignment_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeworkdescription",
            name="students_who_got_it",
            field=models.ManyToManyField(
                through="homework_board_app.Homework", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="my_homeworks",
            field=models.ManyToManyField(
                through="homework_board_app.Homework",
                to="homework_board_app.homeworkdescription",
            ),
        ),
    ]
