# Generated by Django 4.2.5 on 2023-10-03 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("homework_board_app", "0008_homeworkdescription_students_who_got_it_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student", old_name="students_class", new_name="student_class",
        ),
        migrations.RemoveField(model_name="homework", name="homework_description",),
        migrations.RemoveField(model_name="homework", name="student",),
        migrations.RemoveField(model_name="student", name="my_homeworks",),
        migrations.AddField(
            model_name="homework",
            name="assignment_text",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homework",
            name="class_it_is_assigned_to",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="homework_board_app.class",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homework",
            name="date_of_issue",
            field=models.DateField(default="2023-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homework",
            name="deadline_date",
            field=models.DateField(default="2023-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homework",
            name="fines_information",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homework",
            name="students_who_submitted_it",
            field=models.ManyToManyField(
                through="homework_board_app.HomeworkSubmission",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="subject",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="homework_board_app.subject",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homeworksubmission",
            name="student",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="submitted_homeworks",
            field=models.ManyToManyField(
                through="homework_board_app.HomeworkSubmission",
                to="homework_board_app.homework",
            ),
        ),
        migrations.DeleteModel(name="HomeworkDescription",),
    ]
