# Generated by Django 4.2.5 on 2023-10-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "homework_board_app",
            "0009_rename_students_class_student_student_class_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="fio",
            field=models.CharField(default="", max_length=250),
            preserve_default=False,
        ),
    ]
