# Generated by Django 4.2.5 on 2023-10-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homework_board_app", "0010_student_fio"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="name",
            field=models.CharField(default="", max_length=250),
            preserve_default=False,
        ),
    ]
