# Generated by Django 4.2.5 on 2023-10-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homework_board_app", "0011_homework_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="date_of_issue",
            field=models.DateField(auto_now_add=True),
        ),
    ]
