# Generated by Django 4.2.5 on 2023-10-08 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homework_board_app", "0013_alter_student_student_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="date_of_issue",
            field=models.DateField(
                default=datetime.datetime(2023, 10, 9, 1, 20, 9, 572965)
            ),
        ),
    ]
