# Generated by Django 4.2.7 on 2023-11-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_first_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownership",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
