# Generated by Django 4.2.7 on 2023-11-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "project_first_app",
            "0004_alter_carowner_options_alter_carowner_managers_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carowner",
            name="name",
        ),
        migrations.RemoveField(
            model_name="carowner",
            name="surname",
        ),
    ]
