# Generated by Django 4.2.6 on 2023-11-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confapp', '0002_registration_topic_alter_registration_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
