# Generated by Django 4.2.6 on 2023-10-08 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_rename_main_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 8, 14, 9, 46, 808503)),
        ),
        migrations.AddField(
            model_name='homework',
            name='grade',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
