# Generated by Django 4.2.6 on 2023-10-08 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_remove_homework_date_homework_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 8, 15, 37, 7, 69166)),
        ),
        migrations.AlterField(
            model_name='homework',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 8, 15, 37, 7, 69166)),
        ),
    ]
