# Generated by Django 4.2.6 on 2023-10-08 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_alter_homework_end_date_alter_homework_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='homework',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
