# Generated by Django 4.2.6 on 2023-10-08 19:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_alter_homework_end_date_alter_homework_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
