# Generated by Django 4.2.6 on 2023-10-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_profile_profile_picture_alter_homework_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tg_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tw_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
