# Generated by Django 4.2.6 on 2023-10-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_remove_profile_profile_picture_homework_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
