# Generated by Django 4.2.6 on 2023-10-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_remove_homework_score_profile_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworksubmission',
            name='file',
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
