# Generated by Django 4.2.6 on 2023-10-27 13:03

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_remove_homeworksubmission_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='students',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tw_link',
        ),
        migrations.AddField(
            model_name='homework',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='homework',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='homework',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='HomeworkSubmission',
        ),
    ]
