# Generated by Django 4.2.6 on 2023-10-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0017_submittedhomework'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedhomework',
            name='homework_body',
            field=models.TextField(blank=True),
        ),
    ]
