# Generated by Django 4.2.6 on 2023-10-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0018_submittedhomework_homework_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='grade',
        ),
        migrations.AddField(
            model_name='submittedhomework',
            name='grade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submittedhomework',
            name='homework_body',
            field=models.TextField(),
        ),
    ]
