# Generated by Django 4.2.6 on 2023-10-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0020_gradejournal'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='status',
            field=models.CharField(choices=[('issued', 'Issued'), ('pending_review', 'Pending Review'), ('graded', 'Graded')], default='issued', max_length=15),
        ),
    ]
