# Generated by Django 4.2.6 on 2023-10-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0021_homework_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='status',
            field=models.CharField(choices=[('issued', 'Issued'), ('pending_review', 'Pending Review'), ('graded', 'Graded')], max_length=20),
        ),
    ]
