# Generated by Django 4.2.6 on 2023-10-28 11:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0022_alter_homework_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedhomework',
            name='homework_body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
