# Generated by Django 4.2.6 on 2023-10-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0023_alter_submittedhomework_homework_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='status',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='submitted',
        ),
        migrations.AddField(
            model_name='submittedhomework',
            name='status',
            field=models.CharField(choices=[('issued', 'Issued'), ('pending_review', 'Pending Review'), ('graded', 'Graded')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submittedhomework',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
