# Generated by Django 4.2.6 on 2023-10-28 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0024_remove_homework_status_remove_homework_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedhomework',
            name='submission',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.submittedhomework'),
        ),
    ]
