# Generated by Django 4.2.6 on 2023-10-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0025_submittedhomework_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedhomework',
            name='submission',
        ),
    ]
