# Generated by Django 4.2.6 on 2023-10-28 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0026_remove_submittedhomework_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedhomework',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
