# Generated by Django 4.2.6 on 2023-10-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0029_alter_gradejournal_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradejournal',
            name='grade',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
