# Generated by Django 4.2.6 on 2023-10-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0031_alter_gradejournal_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradejournal',
            name='grade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submittedhomework',
            name='grade',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
