# Generated by Django 4.2.6 on 2023-10-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0032_alter_gradejournal_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tg_link',
        ),
        migrations.AddField(
            model_name='profile',
            name='student_class',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
