# Generated by Django 4.2.6 on 2023-10-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0033_remove_profile_tg_link_profile_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='student_class',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
