# Generated by Django 4.2.6 on 2023-10-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0034_homework_student_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('student', 'Student')], max_length=10),
        ),
    ]
