# Generated by Django 4.2.6 on 2023-10-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0037_remove_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='student_class',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
