# Generated by Django 4.2.7 on 2023-11-05 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Racer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
                ('participant_description', models.TextField(max_length=500, null=True)),
                ('experience', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RacerCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_number', models.CharField(max_length=15)),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racing_app.race')),
                ('racer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racing_app.racer')),
            ],
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('lap_time', models.DurationField()),
                ('top_speed', models.FloatField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racing_app.race')),
                ('racer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racing_app.racer')),
            ],
        ),
        migrations.AddField(
            model_name='racer',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='racing_app.racercar'),
        ),
        migrations.AddField(
            model_name='racer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_text', models.TextField()),
                ('comment_type', models.CharField(choices=[('Cooperation', 'Question about cooperation'), ('Race', 'Question about the race'), ('Other', 'Other')], max_length=20)),
                ('rating', models.PositiveIntegerField()),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racing_app.race')),
            ],
        ),
    ]
