# Generated by Django 4.2.7 on 2023-11-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing_app', '0002_race_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='description',
            field=models.CharField(default='Нет описания', max_length=500),
        ),
    ]
