# Generated by Django 4.2.7 on 2023-11-05 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racing_app', '0003_alter_race_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racer',
            name='participant_description',
            field=models.TextField(default='Нет описания', max_length=500),
        ),
        migrations.AlterField(
            model_name='registration',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='racing_app.race'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='racer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='racing_app.racer'),
        ),
    ]
