# Generated by Django 5.0.3 on 2024-03-17 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_alter_meeting_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.game', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meeting.university', verbose_name='Победитель'),
        ),
        migrations.AlterField(
            model_name='gameentry',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.game', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='gameentry',
            name='gamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.gamer', verbose_name='Игрок'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meeting.university', verbose_name='Университет'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.game', verbose_name='Ира'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.university', verbose_name='Университет'),
        ),
    ]
