# Generated by Django 4.2.6 on 2023-10-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_firts_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTable',
        ),
    ]
