site_name: Олейникова_Полина_k33402_№3
dev_addr: '127.0.0.1:9000'
nav:
  - info: info.md
  - urls: urls.md
  - models: models.md
  - views: views.md
  - serializers: serializers.md
  - openapi: openapi_example.md
plugins:
  - render_swagger:
      allow_arbitrary_locations : true