# Generated by Django 4.2.6 on 2023-11-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventcard',
            old_name='status',
            new_name='Status',
        ),
        migrations.AddField(
            model_name='eventcard',
            name='AgeRestriction',
            field=models.CharField(choices=[('18', '18+'), ('16', '16+'), ('12', '12+'), ('0', 'no age restriction')], default=12, max_length=20),
            preserve_default=False,
        ),
    ]
