# Generated by Django 4.2.6 on 2023-12-10 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_site', '0002_rename_status_eventcard_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
