# Generated by Django 4.2.6 on 2023-12-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_site', '0003_delete_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventcard',
            old_name='DateOfPublication',
            new_name='DateOfEvent',
        ),
    ]
