# Generated by Django 4.2.6 on 2023-12-10 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_site', '0004_rename_dateofpublication_eventcard_dateofevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userseventslist',
            name='EventCard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_users_list', to='events_site.eventcard'),
        ),
        migrations.AlterUniqueTogether(
            name='userseventslist',
            unique_together={('EventUser', 'EventCard')},
        ),
    ]
