# Generated by Django 4.2.6 on 2024-01-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_site', '0005_alter_userseventslist_eventcard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userseventslist',
            name='TimeOfRegistration',
            field=models.DateField(auto_now_add=True),
        ),
    ]
