site_name: Отчет по лабораторным работам
theme:
  name: material
nav:
  - Лабораторная №1:
      - task 1: lab1/task_1.md
      - task 2: lab1/task_2.md
      - task 3: lab1/task_3.md
      - task 4: lab1/task_4.md
      - task 5: lab1/task_5.md
      - Выводы: lab1/itog.md
  - Лабораторная №2:
      - models: lab2/models.md
      - forms: lab2/forms.md
      - views: lab2/views.md
      - urls: lab2/urls.md
      - Выводы: lab2/itog.md
  - Практическая №3.1:
      - Создание объектов: pract3/create.md
      - Фильтрация объектов: pract3/filter.md
      - Агрегация и аннотация: pract3/annotate.md
  - Лаюораторная №3:
      - models: lab3/models.md
      - urls: lab3/urls.md
      - filters: lab3/filters.md
      - views: lab3/views.md
      - serializers: lab3/serializers.md
      - settings: lab3/settings.md
      - Выводы: lab3/itog.md