# Generated by Django 4.2.7 on 2023-11-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aviary',
            name='type',
        ),
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.TextField(choices=[('m', 'm'), ('f', 'f')], max_length=2),
        ),
        migrations.AlterField(
            model_name='aviary',
            name='additional',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
