# Generated by Django 5.0.3 on 2024-03-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_remove_aviary_type_alter_animal_sex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviary',
            name='winter_place',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
