# Generated by Django 4.2.7 on 2023-11-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_remove_planemodel_columns_remove_planemodel_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='column',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.CharField(max_length=2),
        ),
    ]
