# Generated by Django 4.2.7 on 2023-11-02 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_alter_reservation_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='flight',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='flight_reservations', to='flights.flight'),
            preserve_default=False,
        ),
    ]
