# Generated by Django 4.2.7 on 2023-11-02 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_reservation_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='plane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plane_flights', to='flights.planemodel'),
        ),
    ]
