# Generated by Django 4.2.10 on 2024-02-24 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество книг')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('date_of_creation', models.DateTimeField()),
                ('type', models.CharField(max_length=120, verbose_name='Раздел')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
                ('books', models.ManyToManyField(related_name='hall_books', through='library_app.Availability', to='library_app.book', verbose_name='Книги')),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_start', models.DateTimeField()),
                ('date_of_end', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.book', verbose_name='Книга')),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=120, verbose_name='ФИО')),
                ('passport', models.IntegerField(verbose_name='Паспорт')),
                ('phone', models.IntegerField(verbose_name='Телефон')),
                ('date_of_birth', models.DateTimeField()),
                ('address', models.CharField(max_length=120, verbose_name='Адрес')),
                ('education', models.CharField(max_length=120, verbose_name='Образование')),
                ('qualification', models.CharField(max_length=120, verbose_name='Учёная степень')),
                ('books', models.ManyToManyField(related_name='reader_books', through='library_app.Ownership', to='library_app.book', verbose_name='Книги')),
                ('hall', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='library_app.hall')),
            ],
        ),
        migrations.AddField(
            model_name='ownership',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.reader', verbose_name='Читатель'),
        ),
        migrations.AddField(
            model_name='book',
            name='halls',
            field=models.ManyToManyField(related_name='book_halls', through='library_app.Availability', to='library_app.hall', verbose_name='Залы'),
        ),
        migrations.AddField(
            model_name='book',
            name='readers',
            field=models.ManyToManyField(related_name='book_readers', through='library_app.Ownership', to='library_app.reader', verbose_name='Читатели'),
        ),
        migrations.AddField(
            model_name='availability',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.book', verbose_name='Книга'),
        ),
        migrations.AddField(
            model_name='availability',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.hall', verbose_name='Зал'),
        ),
        migrations.AlterUniqueTogether(
            name='ownership',
            unique_together={('book', 'reader')},
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('book', 'hall')},
        ),
    ]
