# Generated by Django 3.2.6 on 2024-02-26 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_book_author_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='library_app.hall', verbose_name='Зал'),
        ),
    ]
