site_name: Отчеты по лабораторным работам. Тюлюкин Игорь К33391
nav:
 - Home: index.md
 - Лабораторная №1:
     - "Задание 1": Lab1/Task1.md
     - "Задание 2": Lab1/Task2.md
     - "Задание 3": Lab1/Task3.md
     - "Задание 4": Lab1/Task4.md
     - "Задание 5": Lab1/Task5.md
 - Лабораторная №2:
     - "Описание": Lab2/preview.md
     - "Views.py": Lab2/views.md
     - "Models.py": Lab2/models.md
     - "Urls.py": Lab2/urls.md
     - "Templates": Lab2/templates.md
 - Практика №3:
     - "Практическое задание": Practise3/report.md
 - Лабораторная №3:
     - "Описание": Lab3/preview.md
     - "Views.py": Lab3/views.md
     - "Models.py": Lab3/models.md
     - "Urls.py": Lab3/urls.md
     - "Serializers.py": Lab3/serializers.md
 - Лабораторная №4:
     - "Описание": Lab4/preview.md
     - "main.ts": Lab4/app.md
     - "router.ts": Lab4/router.md
     - "EditingProgram.vue": Lab4/EditingProgram.md
theme:
  name: material
  features:
    - content.code.annotate
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences