# Generated by Django 4.2.7 on 2023-11-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_alter_carowner_managers_carowner_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='birth_date',
            field=models.DateTimeField(null=True),
        ),
    ]
