# Generated by Django 4.2.7 on 2023-11-09 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "contentobject_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="website.contentobject",
                    ),
                ),
                (
                    "attached_file",
                    models.FileField(
                        blank=True, null=True, upload_to="files/publications"
                    ),
                ),
                ("external_reference_link", models.URLField(blank=True, null=True)),
            ],
            options={"abstract": False, "base_manager_name": "objects",},
            bases=("website.contentobject",),
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterModelOptions(
            name="newspaper", options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="newtone", options={"base_manager_name": "objects"},
        ),
        migrations.RemoveField(model_name="newspaper", name="attached_file",),
        migrations.RemoveField(model_name="newspaper", name="contentobject_ptr",),
        migrations.RemoveField(model_name="newspaper", name="external_reference_link",),
        migrations.RemoveField(model_name="newtone", name="attached_file",),
        migrations.RemoveField(model_name="newtone", name="contentobject_ptr",),
        migrations.RemoveField(model_name="newtone", name="external_reference_link",),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.contentobject",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="website.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="newspaper",
            name="publication_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="website.publication",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="newtone",
            name="publication_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="website.publication",
            ),
            preserve_default=False,
        ),
    ]
