# Generated by Django 4.2.7 on 2023-11-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_publication_role_alter_newspaper_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcastissue", name="n_issue", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="publication",
            name="attached_file",
            field=models.FileField(
                blank=True, null=True, upload_to="files/publications/"
            ),
        ),
    ]
