# Generated by Django 4.2.7 on 2023-11-09 19:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_alter_podcastissue_n_issue_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "n_amongst_banners",
                    models.IntegerField(
                        default=1,
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                (
                    "special_cover_picture",
                    models.ImageField(
                        default="images/alt_image.jpg",
                        null=True,
                        upload_to="images/banner/",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="website.article",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="banner",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("n_amongst_banners__gte", 1), ("n_amongst_banners__lt", 6)
                ),
                name="There can only be 6 consequent banners",
            ),
        ),
    ]
