# Generated by Django 4.2.7 on 2023-11-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_banner_banner_there_can_only_be_6_consequent_banners"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="whatwedo",
            options={
                "verbose_name": "Что мы делаем",
                "verbose_name_plural": "Что мы делаем",
            },
        ),
        migrations.AlterField(
            model_name="whatwedo",
            name="cover_picture",
            field=models.ImageField(
                default="images/alt_image.jpg",
                null=True,
                upload_to="images/what_we_do/",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="whatwedo",
            name="external_reference_link",
            field=models.URLField(blank=True, null=True, verbose_name="Внешняя ссылка"),
        ),
        migrations.AlterField(
            model_name="whatwedo",
            name="is_displayed",
            field=models.BooleanField(default=False, verbose_name="Отображается"),
        ),
        migrations.AlterField(
            model_name="whatwedo",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="whatwedo",
            name="short_description",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Краткое описание"
            ),
        ),
    ]
