# Generated by Django 4.2.7 on 2023-11-09 21:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_podcastlink_alter_article_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Дата регистрации",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="patronymic",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Отчество"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_info",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Биография"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                default="images/alt_image.jpg",
                null=True,
                upload_to="images/users/",
                verbose_name="Аватарка",
            ),
        ),
    ]
