# Generated by Django 4.2.7 on 2023-11-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_alter_user_date_joined_alter_user_patronymic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                default="images/alt_image.jpg",
                null=True,
                upload_to="images/users/",
                verbose_name="Аватар",
            ),
        ),
    ]
