# Generated by Django 4.2.7 on 2023-11-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentobject",
            name="is_hidden",
            field=models.BooleanField(default=False, verbose_name="Скрыть объект"),
        ),
    ]
