# Generated by Django 4.2.7 on 2023-11-11 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_contentobject_is_hidden"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250, unique=True, verbose_name="Название"
                    ),
                ),
            ],
            options={"verbose_name": "Хэштег", "verbose_name_plural": "Хэштеги",},
        ),
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Название")),
                (
                    "base_reference_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на платформу"
                    ),
                ),
            ],
            options={"verbose_name": "Платформа", "verbose_name_plural": "Платформы",},
        ),
        migrations.RemoveField(model_name="participant", name="content_object",),
        migrations.AddField(
            model_name="participant",
            name="article",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.article",
                verbose_name="Статья",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contentobject",
            name="release_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата создания"),
        ),
        migrations.CreateModel(
            name="Hashtags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.article",
                        verbose_name="Статья",
                    ),
                ),
                (
                    "hashtag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.hashtag",
                        verbose_name="Хэштег",
                    ),
                ),
            ],
            options={
                "verbose_name": "Хэштег у статьи",
                "verbose_name_plural": "Хэштеги у статей",
            },
        ),
        migrations.AlterField(
            model_name="podcastlink",
            name="platform",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="website.platform",
                verbose_name="Платформа",
            ),
        ),
    ]
