# Generated by Django 4.2.7 on 2023-11-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_hashtag_platform_remove_participant_content_object_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_team_member",
            field=models.BooleanField(default=False),
        ),
    ]
