# Generated by Django 4.2.7 on 2023-11-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_user_is_team_member"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Название")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="Про команду"
                    ),
                ),
            ],
            options={"verbose_name": "Команда", "verbose_name_plural": "Команда",},
        ),
    ]
