# Generated by Django 4.2.7 on 2023-11-11 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0012_team"),
    ]

    operations = [
        migrations.DeleteModel(name="Team",),
    ]
