# Generated by Django 4.2.7 on 2023-11-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0013_delete_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_team_member",
            field=models.BooleanField(default=False, verbose_name="Член команды"),
        ),
    ]
