# Generated by Django 4.2.7 on 2023-11-11 10:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0014_alter_user_is_team_member"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "n_amongst_pages",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Номер страницы в выпуске",
                    ),
                ),
                (
                    "attached_page_file",
                    models.FileField(
                        upload_to="files/publication_pages/",
                        verbose_name="Файл (pdf/png/jpg)",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.article",
                        verbose_name="Связанная со страницей статья",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.publication",
                        verbose_name='Публикация "на бумаге"',
                    ),
                ),
            ],
            options={
                "verbose_name": "Отдельная страница публикации",
                "verbose_name_plural": "Отдельные страницы публикации",
            },
        ),
        migrations.AddConstraint(
            model_name="publicationpage",
            constraint=models.CheckConstraint(
                check=models.Q(("n_amongst_pages__gte", 1)),
                name="Номер страницы должен быть положительным числом",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="publicationpage",
            unique_together={("publication", "n_amongst_pages")},
        ),
    ]
