# Generated by Django 4.2.7 on 2023-11-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0015_publicationpage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Полное имя"
            ),
        ),
    ]
