# Generated by Django 4.2.7 on 2023-11-12 09:54

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0016_user_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=tinymce.models.HTMLField(verbose_name="Содержание"),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Дата регистрации"
            ),
        ),
    ]
