# Generated by Django 4.2.7 on 2023-11-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0017_alter_article_content_alter_user_date_joined"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("position_x", models.IntegerField(default=0)),
                ("position_y", models.IntegerField(default=0)),
            ],
        ),
    ]
