# Generated by Django 4.2.7 on 2023-11-12 20:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0018_textblock"),
    ]

    operations = [
        migrations.DeleteModel(name="TextBlock",),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=ckeditor.fields.RichTextField(verbose_name="Содержание"),
        ),
    ]
