# Generated by Django 4.2.7 on 2023-11-12 20:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0019_delete_textblock_alter_article_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Содержание"
            ),
        ),
    ]
