# Generated by Django 4.2.7 on 2023-11-14 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0020_alter_article_content"),
    ]

    operations = [
        migrations.RemoveField(model_name="whatwedo", name="is_displayed",),
    ]
