# Generated by Django 4.2.7 on 2023-11-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0021_remove_whatwedo_is_displayed"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="article_hashtags",
            field=models.ManyToManyField(
                through="website.Hashtags", to="website.hashtag", verbose_name="Хэштеги"
            ),
        ),
        migrations.AddField(
            model_name="hashtag",
            name="hashtag_articles",
            field=models.ManyToManyField(
                through="website.Hashtags", to="website.article", verbose_name="Статьи"
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="special_cover_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/banner/",
                verbose_name="Специальная картинка обложки",
            ),
        ),
    ]
