# Generated by Django 4.2.7 on 2023-11-17 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0022_article_article_hashtags_hashtag_hashtag_articles_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="article_participants",
            field=models.ManyToManyField(
                through="website.Participant",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Участники в создании",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="article_participated",
            field=models.ManyToManyField(
                through="website.Participant",
                to="website.article",
                verbose_name="Участники в создании",
            ),
        ),
    ]
