# Generated by Django 4.2.7 on 2023-11-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0023_article_article_participants_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favourites",
            field=models.ManyToManyField(
                related_name="favs",
                through="website.Favourite",
                to="website.contentobject",
                verbose_name="Избранное",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="article_participated",
            field=models.ManyToManyField(
                related_name="parts",
                through="website.Participant",
                to="website.article",
                verbose_name="Участники в создании",
            ),
        ),
    ]
