# Generated by Django 4.2.7 on 2023-11-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0024_user_favourites_alter_user_article_participated"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="podcast_platforms",
            field=models.ManyToManyField(
                through="website.PodcastLink",
                to="website.platform",
                verbose_name="Платформы",
            ),
        ),
    ]
