# Generated by Django 5.0 on 2023-12-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musec_app', '0003_file_alter_apitoken_user_alter_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='patronymic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
