# Generated by Django 5.0 on 2024-01-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musec_app', '0005_remove_file_extension_remove_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('audio', 'audio'), ('video', 'video'), ('image', 'image')], default='audio', max_length=5),
            preserve_default=False,
        ),
    ]
