site_name: "Рашевский_Вячеслав_K33402_Лабораторные_работы"
nav:
  - "№1: Сокеты":
      - index.md
      - task1.md
      - task2.md
      - task3.md
      - task4.md
      - task5.md
      - leetcode.md