# Generated by Django 4.2.7 on 2023-11-05 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_hotel_owner_user_password_user_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='price',
        ),
    ]
