# Generated by Django 4.2.7 on 2023-11-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_remove_room_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Checked In', 'Checked In'), ('Completed', 'Completed')], max_length=200, null=True),
        ),
    ]
