# Generated by Django 4.2.7 on 2023-11-05 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
