# Generated by Django 4.2.7 on 2023-11-06 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0016_remove_review_id_remove_review_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='review', serialize=False, to='hotels.booking'),
        ),
    ]
