# Generated by Django 4.2.7 on 2023-11-18 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_number', models.CharField(max_length=15, blank=False)),
                ('brand', models.CharField(max_length=20, blank=False)),
                ('model', models.CharField(max_length=20, blank=False)),
                ('colour', models.CharField(max_length=30, blank=True)),
            ],
        ),
    ]
