# Generated by Django 4.2.6 on 2023-11-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dismissal_agreement_id',
            field=models.IntegerField(null=True),
        ),
    ]
