# Generated by Django 4.2.6 on 2024-01-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
