# Generated by Django 4.2.6 on 2024-01-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_comment__type'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
