# Generated by Django 4.2.6 on 2024-01-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_register_time_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='_type',
            field=models.CharField(choices=[('collaboration', 'collaboration'), ('racing', 'racing'), ('other', 'other')], default='collaboration', max_length=100),
        ),
    ]
