# Generated by Django 4.2.6 on 2024-01-04 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_comment__type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='_type',
            new_name='type',
        ),
    ]
