# Generated by Django 5.0.3 on 2024-03-12 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homework', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='user.teacher'),
        ),
        migrations.AddField(
            model_name='homework',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='homework.subject'),
        ),
        migrations.AddField(
            model_name='subjectteacher',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.subject'),
        ),
        migrations.AddField(
            model_name='subjectteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.teacher'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(related_name='subjects', through='homework.SubjectTeacher', to='user.teacher'),
        ),
        migrations.AddField(
            model_name='submission',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework.homework'),
        ),
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='user.student'),
        ),
        migrations.AddField(
            model_name='grade',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='homework.submission'),
        ),
        migrations.AddIndex(
            model_name='subjectteacher',
            index=models.Index(fields=['subject', 'teacher'], name='homework_su_subject_e6a520_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectteacher',
            unique_together={('subject', 'teacher')},
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['homework', 'student'], name='homework_su_homewor_7bf898_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('homework', 'student')},
        ),
    ]
