# Generated by Django 4.2.6 on 2023-10-19 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("airtravel_scoreboard_app", "0002_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="airtravel_scoreboard_app.flight",
            ),
        ),
    ]
