# Generated by Django 5.0 on 2023-12-21 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musec_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
