# Generated by Django 4.2.7 on 2023-11-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_management', '0002_alter_reservation_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='booked_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='total_seats',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
