# Generated by Django 4.2.6 on 2023-11-27 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillofwarrior',
            name='level',
            field=models.IntegerField(blank=True, null=True, verbose_name='Уровень освоения умения'),
        ),
        migrations.AlterField(
            model_name='skillofwarrior',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.skill', verbose_name='Умение'),
        ),
        migrations.AlterField(
            model_name='skillofwarrior',
            name='warrior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warrior_skill', to='myapp.warrior', verbose_name='Воин'),
        ),
    ]
