# Generated by Django 3.2.22 on 2023-10-14 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerShipUpdated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.car')),
                ('owners', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.helpingtable')),
            ],
        ),
        migrations.AddField(
            model_name='helpingtable',
            name='car',
            field=models.ManyToManyField(to='blog.Car'),
        ),
    ]
