# Generated by Django 3.2.22 on 2023-10-15 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20231015_0122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OwnerShipUpdated',
            new_name='CarToPerson',
        ),
    ]
