# Generated by Django 3.2.22 on 2023-10-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20231015_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpingtable',
            name='car',
        ),
        migrations.RemoveField(
            model_name='helpingtable',
            name='person',
        ),
        migrations.DeleteModel(
            name='CarToPerson',
        ),
        migrations.DeleteModel(
            name='HelpingTable',
        ),
    ]
