# Generated by Django 3.2.22 on 2023-10-15 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20231015_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarToPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.car')),
            ],
        ),
        migrations.CreateModel(
            name='HelpingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ManyToManyField(to='blog.Car')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.person')),
            ],
        ),
        migrations.AddField(
            model_name='cartoperson',
            name='cars',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.helpingtable'),
        ),
        migrations.AddField(
            model_name='cartoperson',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.person'),
        ),
    ]
