# Generated by Django 3.2.22 on 2023-10-15 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20231015_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoperson',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.person'),
        ),
    ]
