# Generated by Django 3.2.22 on 2023-10-15 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_cartoperson_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpingtable',
            name='car',
            field=models.ManyToManyField(to='blog.Person'),
        ),
        migrations.AlterField(
            model_name='helpingtable',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.car'),
        ),
    ]
