# Generated by Django 3.2.22 on 2023-10-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20231015_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpingtable',
            name='car',
            field=models.ManyToManyField(to='blog.Car'),
        ),
        migrations.DeleteModel(
            name='CarToPerson',
        ),
    ]
