# Generated by Django 3.2.22 on 2023-10-15 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20231015_1315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpingTable',
        ),
    ]
