# Generated by Django 3.2.22 on 2023-10-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
