# Generated by Django 3.2.22 on 2023-10-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20231015_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='nationality',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='passport',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
