# Generated by Django 3.2.22 on 2023-10-15 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_person_address'),
    ]

    operations = [
    ]
