# Generated by Django 3.2.22 on 2023-10-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_person_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nationality',
            field=models.CharField(default='No ethnicity', max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='passport',
            field=models.CharField(default='No passport', max_length=20),
        ),
    ]
