# Generated by Django 3.2.22 on 2023-10-15 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0040_auto_20231015_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personadvanced',
            name='user',
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
