# Generated by Django 4.2.6 on 2023-10-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("air_tickets_booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="passport",
            field=models.CharField(max_length=30),
        ),
    ]
