# Generated by Django 4.2.6 on 2023-10-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "air_tickets_booking",
            "0002_alter_user_date_of_birth_alter_user_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="seat",
            field=models.CharField(default="aaa", max_length=10),
            preserve_default=False,
        ),
    ]
