# Generated by Django 4.2.6 on 2023-11-05 20:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='available_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), default=list, size=None, verbose_name='Доступные даты'),
        ),
    ]
