# Generated by Django 5.0.2 on 2024-02-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_table_app', '0002_alter_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='arrival_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
