# Generated by Django 4.2.7 on 2024-01-10 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('air_travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='comment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='air_travel.comments'),
            preserve_default=False,
        ),
    ]
