# Generated by Django 4.2.7 on 2024-01-11 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('air_travel', '0003_alter_booking_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='booking',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='air_travel.booking'),
            preserve_default=False,
        ),
    ]
