# Generated by Django 4.2.6 on 2023-11-27 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise_app', '0001_initial'),
        ('chicken_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicken',
            name='cage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise_app.cage'),
        ),
        migrations.AddField(
            model_name='breed',
            name='recommended_diet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chicken_app.diet'),
        ),
    ]
