# Generated by Django 4.2.6 on 2023-11-28 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_app', '0002_alter_user_dismissal_agreement_id'),
        ('chicken_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicken',
            name='cage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cage_chicken', to='enterprise_app.cage'),
        ),
    ]
