# Generated by Django 4.2.6 on 2023-12-17 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год обучения')),
                ('litera', models.CharField(choices=[('A', 'А'), ('B', 'Б'), ('C', 'Ц')], max_length=1, verbose_name='Буква')),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('klass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.classes', verbose_name='Класс')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=120, verbose_name='ФИО')),
                ('name', models.CharField(choices=[('Math', 'Математика'), ('Physics', 'Физика'), ('Arts', 'Искусства'), ('Music', 'Музыка'), ('Chemisty', 'Химия'), ('Sports', 'Физра'), ('Languanges', 'Языки'), ('Literature', 'Литература')], max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('cabinet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='school_app.cabinets')),
                ('FIO', models.CharField(max_length=120, verbose_name='ФИО')),
                ('classroom_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.teachers', verbose_name='Учитель')),
            ],
        ),
        migrations.CreateModel(
            name='Teachings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(verbose_name='Стаж')),
                ('klasses', models.ManyToManyField(related_name='teaching_classes', through='school_app.Schedules', to='school_app.classes', verbose_name='Классы')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.subjects', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.teachers', verbose_name='Учитель')),
            ],
        ),
        migrations.AddField(
            model_name='schedules',
            name='teaching',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.teachings', verbose_name='Преподавание'),
        ),
        migrations.AddField(
            model_name='classes',
            name='teachings',
            field=models.ManyToManyField(related_name='class_teachings', through='school_app.Schedules', to='school_app.teachings', verbose_name='Преподавания'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='subjects',
            field=models.ManyToManyField(related_name='teacher_subjects', through='school_app.Teachings', to='school_app.subjects', verbose_name='Предметы'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='teachers',
            field=models.ManyToManyField(related_name='subject_teachers', through='school_app.Teachings', to='school_app.teachers', verbose_name='Учителя'),
        ),
        migrations.AddField(
            model_name='classes',
            name='classroom_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.teachers', verbose_name='Учителя'),
        ),
    ]
