# Generated by Django 4.2.6 on 2023-12-18 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0005_alter_teachers_cabinet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='classroom_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.teachers', verbose_name='Классный руководитель'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject',
            field=models.CharField(choices=[('Math', 'Математика'), ('Physics', 'Физика'), ('Arts', 'Искусства'), ('Music', 'Музыка'), ('Chemisty', 'Химия'), ('Sports', 'Физра'), ('Languanges', 'Языки'), ('Literature', 'Литература')], max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
