# Generated by Django 4.2.6 on 2023-11-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='guest',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_photos'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='hotel_photos'),
        ),
        migrations.AlterField(
            model_name='room',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='room_photos'),
        ),
    ]
