# Generated by Django 4.2.6 on 2023-11-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_alter_guest_options_alter_hotel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='country',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
