# Generated by Django 4.2.6 on 2023-11-02 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0003_alter_guest_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='country',
        ),
    ]
