# Generated by Django 4.2.6 on 2023-11-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0005_guest_country_alter_guest_about_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='about_info',
            field=models.TextField(default='A very interesting person'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='country',
            field=models.CharField(default='Russia', max_length=64),
        ),
        migrations.AlterField(
            model_name='guest',
            name='profile_picture',
            field=models.ImageField(default='user.svg', upload_to='profile_photos'),
        ),
    ]
