# Generated by Django 4.2.6 on 2023-11-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0006_alter_guest_about_info_alter_guest_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='profile_picture',
            field=models.ImageField(default='profile_photos/user.svg', upload_to='profile_photos'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('AW', 'Awaits'), ('FI', 'Finished'), ('CA', 'Cancelled')], default='AW', max_length=2),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('1', '★☆☆☆☆☆☆☆☆☆'), ('2', '★★☆☆☆☆☆☆☆☆'), ('3', '★★★☆☆☆☆☆☆☆'), ('4', '★★★★☆☆☆☆☆☆'), ('5', '★★★★★☆☆☆☆☆'), ('6', '★★★★★★☆☆☆☆'), ('7', '★★★★★★★☆☆☆'), ('8', '★★★★★★★★☆☆'), ('9', '★★★★★★★★★☆'), ('10', '★★★★★★★★★★')]),
        ),
    ]
