# Generated by Django 4.2.6 on 2023-12-17 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('1', 'Кол'), ('2', 'Неудовлетворительно'), ('3', 'Удовлетворительно'), ('4', 'Хорошо'), ('5', 'Отлично')], max_length=50, verbose_name='Оценка')),
                ('attendance', models.BooleanField(blank=True, null=True)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.schedules', verbose_name='Предмет в расписании')),
            ],
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='name',
            new_name='subject',
        ),
        migrations.AlterUniqueTogether(
            name='teachings',
            unique_together={('teacher', 'subject')},
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=120, verbose_name='ФИО')),
                ('klass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.classes', verbose_name='Класс')),
                ('schedules', models.ManyToManyField(related_name='student_schedules', through='school_app.Grades', to='school_app.schedules', verbose_name='Занятия')),
            ],
        ),
        migrations.AddField(
            model_name='grades',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.students', verbose_name='Ученик'),
        ),
        migrations.AddField(
            model_name='schedules',
            name='students',
            field=models.ManyToManyField(related_name='schedule_students', through='school_app.Grades', to='school_app.students', verbose_name='Ученики'),
        ),
    ]
