# Generated by Django 4.2.6 on 2023-12-18 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_grades_rename_name_subjects_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='FIO',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='classroom_teacher',
        ),
    ]
