# Generated by Django 4.2.6 on 2024-01-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0007_alter_subjects_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='schedules',
            field=models.ManyToManyField(blank=True, related_name='student_schedules', through='school_app.Grades', to='school_app.schedules', verbose_name='Занятия'),
        ),
    ]
