# Generated by Django 4.2.7 on 2023-11-24 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=16, unique=True)),
                ('airline_name', models.CharField(choices=[('AEROFLOT', 'Aeroflot'), ('BRIT_AIR', 'British Airlines'), ('LUFTHANSA', 'Lufthansa'), ('TURK_AIR', 'Turkish Airlines'), ('AIR_FRANCE', 'Air France')], max_length=32)),
                ('departure', models.DateTimeField()),
                ('arrival', models.DateTimeField()),
                ('origin', models.CharField(choices=[('AMS', 'Amsterdam'), ('BER', 'Berlin'), ('CPH', 'Copenhagen'), ('DUB', 'Dublin'), ('HEL', 'Helsinki'), ('SVO', 'Moscow (Sheremetyevo)'), ('LHR', 'London (Heathrow)'), ('LED', 'Saint-Petersburg (Pulkovo)')], max_length=3)),
                ('destination', models.CharField(choices=[('AMS', 'Amsterdam'), ('BER', 'Berlin'), ('CPH', 'Copenhagen'), ('DUB', 'Dublin'), ('HEL', 'Helsinki'), ('SVO', 'Moscow (Sheremetyevo)'), ('LHR', 'London (Heathrow)'), ('LED', 'Saint-Petersburg (Pulkovo)')], max_length=3)),
                ('type', models.CharField(choices=[('ARR', 'Arrival'), ('DEP', 'Departure')], max_length=9)),
                ('gate_number', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'flight',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=4, null=True)),
                ('checked_in', models.BooleanField(default=False)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('flight', 'seat_number')},
            },
        ),
        migrations.AddField(
            model_name='flight',
            name='passengers',
            field=models.ManyToManyField(through='airport.Reservation', to=settings.AUTH_USER_MODEL),
        ),
    ]
