# Generated by Django 4.2.7 on 2023-11-24 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'reservation'},
        ),
    ]
