# Generated by Django 4.2.7 on 2023-11-24 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_alter_reservation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={},
        ),
        migrations.AlterModelTable(
            name='reservation',
            table='reservation',
        ),
    ]
