# Generated by Django 4.2.7 on 2023-11-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0003_alter_reservation_options_alter_reservation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='ticket_number',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
