# Generated by Django 4.2.7 on 2023-11-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0004_reservation_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='seat_number',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
