# Generated by Django 4.2.5 on 2023-11-01 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project_first_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carowner",
            name="cars",
            field=models.ManyToManyField(
                related_name="owners",
                through="project_first_app.Ownership",
                to="project_first_app.car",
            ),
        ),
        migrations.AlterField(
            model_name="drivinglicense",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="licenses",
                to="project_first_app.carowner",
            ),
        ),
        migrations.AlterField(
            model_name="ownership",
            name="car",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ownerships",
                to="project_first_app.car",
            ),
        ),
        migrations.AlterField(
            model_name="ownership",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ownerships",
                to="project_first_app.carowner",
            ),
        ),
    ]
