# Generated by Django 4.2.6 on 2023-12-19 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefloor',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee_floor_set', to='hotel_api.room'),
            preserve_default=False,
        ),
    ]
