# Generated by Django 4.2.7 on 2023-11-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alpinism_app", "0005_alter_clubmembership_date_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubmembership",
            name="date_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mountain",
            name="area",
            field=models.CharField(max_length=100),
        ),
    ]
