# Generated by Django 5.0.3 on 2024-03-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing_club', '0003_alter_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racer',
            name='biography',
            field=models.TextField(null=True, verbose_name='Racer biography'),
        ),
    ]
