# Generated by Django 4.2.7 on 2023-11-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='country',
            field=models.CharField(default='Belarus', max_length=200),
            preserve_default=False,
        ),
    ]
