# Generated by Django 4.2.7 on 2023-11-23 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="broker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="broker_account",
                to="exchange_app.broker",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manufacturer_account",
                to="exchange_app.manufacturer",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("b", "broker"),
                    ("m", "manufacturer"),
                    ("e", "exchange-admin"),
                ],
                default="e",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="consignment",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                through="exchange_app.ProductInConsignment",
                to="exchange_app.product",
            ),
        ),
    ]
