# Generated by Django 4.2.7 on 2023-11-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_app", "0003_product_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consignment",
            name="status",
            field=models.CharField(
                choices=[("a", "active"), ("c", "cancelled"), ("s", "signed")],
                default="a",
                max_length=1,
            ),
        ),
    ]
