# Generated by Django 4.2.7 on 2023-11-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_app", "0004_alter_consignment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consignment",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("a", "active"), ("c", "cancelled"), ("s", "signed")],
                default="a",
                max_length=1,
            ),
        ),
    ]
