site_name: Web-программирование
site_description: Лабораторные работы по курсу Web-программирование
site_author: Бускина Алия
repo_url: https://github.com/AliiaBuskina/ITMO_ICT_WebDevelopment_2023-2024
edit_uri: ""

theme:
  palette:
    primary: deep blue
  name: material
  language: ru
  features:
    - header.autohide

nav:
  - 'Главная страница': 'home.md'
  - 'Лабораторная работа №1':
    - 'Задание №1': 'lab1_1.md'
    - 'Задание №2': 'lab1_2.md'
    - 'Задание №3': 'lab1_3.md'
    - 'Задание №4': 'lab1_4.md'
    - 'Задание №5': 'lab1_5.md'

extra:
  homepage: 'home.md'
