# Generated by Django 4.2.6 on 2023-10-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_remove_room_amenities_remove_room_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest_name',
            field=models.CharField(default='Неизвестный гость', max_length=200, verbose_name='Guest Name'),
        ),
    ]
