# Generated by Django 4.2.7 on 2023-11-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_reservation_guest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='imageURL',
            field=models.URLField(default='kek'),
            preserve_default=False,
        ),
    ]
