# Generated by Django 4.2.7 on 2023-11-29 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_hotel_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
    ]
