site_name: Lab works documentation
theme:
  name: material

repo_url: https://github.com/elderberry17/ITMO_ICT_WebDevelopment_2023-2024
repo_name: elderberry17/ITMO_ICT_WebDevelopment
nav:
  - "№1: Сокеты":
      - lw1/task1.md
      - lw1/task2.md
      - lw1/task3.md
      - lw1/task4.md
      - lw1/task5.md
  - "№2: Табло перелетов":
      - lw2/index.md
      - lw2/models.md
      - lw2/forms.md
      - lw2/views.md
      - lw2/urls.md