# Generated by Django 4.2.6 on 2023-12-02 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_exchange_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerequest',
            name='book_offered',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_exchange_app.book'),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
