name: Deploy Website Lr2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install mkdocs

      - name: Build
        run: mkdocs build

      - name: Deploy
        run: |
          git config user.name "Makunina Arina"
          git config user.email "actions@users.noreply.github.com"
          git checkout gh-pages
          git pull
          cp -r site/* .
          git add .
          git commit -m "Deployed website for Lr2"
          git push
