site_name: Пронина Александра K33392
theme:
  name: mkdocs
  features:
    - navigation.indexes
  palette:
    scheme: slate
    primary: white
    accent: purple
nav:
  - Лабораторная работа №3:
      - Титульная страница: lr3/index.md
      - Работа: lr3/main.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html
