site_name: 'Лабораторные работы'
theme:
  name: material
  features:
    - navigation.indexes
    - content.code.copy
  icon:
    repo: fontawesome/brands/github-alt
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/weather-night
        name: Темная тема
    - media: '(prefers-color-scheme: dark)'
      primary: black
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Светлая тема
  language: ru
repo_url: https://github.com/TUTOR03/ITMO_ICT_WebDevelopment_2023-2024
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: '../'
  - pymdownx.superfences
  - pymdownx.keys
plugins:
  - glightbox:
      auto_caption: true
nav:
  - '№1: Сокеты':
      - lab1/task_1.md
      - lab1/task_2.md
      - lab1/task_3.md
      - lab1/task_4.md
      - lab1/task_5.md
  - '№2: Django':
      - lab2/configuration.md
      - lab2/models.md
      - lab2/forms.md
      - lab2/urls.md
      - lab2/views.md
      - lab2/templates.md
  - '№3.1: Практическая 3.1':
      - prac3_1/task_1.md
      - prac3_1/task_2.md
      - prac3_1/task_3.md
  - '№3: REST framework':
      - lab3/configuration.md
      - lab3/urls.md
      - lab3/models.md
      - lab3/views.md
