# Generated by Django 4.2.7 on 2023-11-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first_app', '0002_alter_ownership_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='start_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
